'use client';

import { useState } from 'react';

const cloudIdeas = [
  'My best holiday ever',
  'I feel happy when...',
  'The most exciting adventure',
  'A person I admire',
];

const whPrompts = [
  { q: 'Who?', hint: 'Who is involved in your story?' },
  { q: 'What?', hint: 'What happened or will happen?' },
  { q: 'Where?', hint: 'Where does the story take place?' },
  { q: 'When?', hint: 'When did it happen?' },
  { q: 'Why?', hint: 'Why did it happen or why is it important?' },
  { q: 'How?', hint: 'How did it make you feel or how was it resolved?' },
];

export default function RaindropMethod() {
  const [selectedIdea, setSelectedIdea] = useState(0);
  const [activePhase, setActivePhase] = useState<'cloud' | 'raindrops' | 'ground'>('cloud');

  const sampleNarrative = `My most memorable holiday was when I visited Langkawi with my family during the school break. It happened in December last year. The crystal-clear waters and golden beaches made it feel like paradise. More importantly, this trip taught me the value of spending quality time with loved ones. I learned that happiness is not about grand adventures but about the simple moments shared with family.`;

  return (
    <section id="innovations">
      <div className="mb-8">
        <h2 className="text-2xl md:text-3xl font-bold text-primary">Pedagogical Innovations</h2>
        <p className="text-gray-500 mt-1">Signature Innovation Showcase — The Raindrop Method for ESL Narrative Mastery</p>
      </div>

      <div className="flex justify-center gap-2 mb-8">
        {(['cloud', 'raindrops', 'ground'] as const).map((phase) => (
          <button
            key={phase}
            onClick={() => setActivePhase(phase)}
            className={`px-4 py-2 rounded-full text-sm font-medium transition-all ${
              activePhase === phase
                ? 'bg-primary text-white shadow-lg'
                : 'bg-gray-100 text-gray-600 hover:bg-gray-200'
            }`}
          >
            {phase === 'cloud' ? '☁️ The Cloud' : phase === 'raindrops' ? '🌧️ The Raindrops' : '🌱 The Ground'}
          </button>
        ))}
      </div>

      <div className="space-y-6">
        {/* The Cloud */}
        <div
          className={`rounded-2xl p-6 md:p-8 transition-all duration-500 ${
            activePhase === 'cloud'
              ? 'bg-blue-50 border-2 border-blue-200 shadow-lg scale-100 opacity-100'
              : 'bg-gray-50 border-2 border-gray-100 scale-95 opacity-60'
          }`}
        >
          <div className="flex items-center gap-2 mb-4">
            <span className="text-2xl">☁️</span>
            <h3 className="text-lg font-bold text-primary">The Cloud — Broad Ideas</h3>
          </div>
          <p className="text-sm text-gray-600 mb-4">
            Unstructured creative writing ideas generated by weak-to-intermediate language learners.
          </p>
          <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
            {cloudIdeas.map((idea, i) => (
              <button
                key={i}
                onClick={() => setSelectedIdea(i)}
                className={`p-3 rounded-xl text-sm font-medium transition-all ${
                  selectedIdea === i
                    ? 'bg-blue-500 text-white shadow-md'
                    : 'bg-white text-gray-700 border border-gray-200 hover:border-blue-300'
                }`}
              >
                {idea}
              </button>
            ))}
          </div>
        </div>

        {/* The Raindrops */}
        <div
          className={`rounded-2xl p-6 md:p-8 transition-all duration-500 ${
            activePhase === 'raindrops'
              ? 'bg-indigo-50 border-2 border-indigo-200 shadow-lg scale-100 opacity-100'
              : 'bg-gray-50 border-2 border-gray-100 scale-95 opacity-60'
          }`}
        >
          <div className="flex items-center gap-2 mb-4">
            <span className="text-2xl">🌧️</span>
            <h3 className="text-lg font-bold text-primary">The Raindrops — Structured Scaffolding (CT Decomposition)</h3>
          </div>
          <p className="text-sm text-gray-600 mb-4">
            Computational Thinking decomposition — broad ideas segmented into directed WH-Question prompts.
          </p>
          <div className="grid grid-cols-2 md:grid-cols-3 gap-3">
            {whPrompts.map((prompt, i) => (
              <div key={i} className="bg-white rounded-xl p-4 border border-indigo-100 hover:shadow-md transition-shadow">
                <span className="inline-block px-2 py-0.5 bg-indigo-100 text-indigo-700 text-xs font-bold rounded mb-2">
                  {prompt.q}
                </span>
                <p className="text-xs text-gray-500">{prompt.hint}</p>
              </div>
            ))}
          </div>
        </div>

        {/* The Ground */}
        <div
          className={`rounded-2xl p-6 md:p-8 transition-all duration-500 ${
            activePhase === 'ground'
              ? 'bg-green-50 border-2 border-green-200 shadow-lg scale-100 opacity-100'
              : 'bg-gray-50 border-2 border-gray-100 scale-95 opacity-60'
          }`}
        >
          <div className="flex items-center gap-2 mb-4">
            <span className="text-2xl">🌱</span>
            <h3 className="text-lg font-bold text-primary">The Ground — Cohesive Narrative Output</h3>
          </div>
          <p className="text-sm text-gray-600 mb-4">
            Final cohesive narrative with plot sequencing and personal reflection — demonstrating transition from low mastery to independent proficiency.
          </p>
          <div className="bg-white rounded-xl p-5 border border-green-100">
            <div className="flex items-center gap-2 mb-3">
              <span className="w-2 h-2 bg-green-500 rounded-full animate-pulse" />
              <span className="text-xs font-semibold text-green-600 uppercase tracking-wider">Final Narrative</span>
            </div>
            <p className="text-sm text-gray-700 leading-relaxed italic">
              &ldquo;{sampleNarrative}&rdquo;
            </p>
          </div>
        </div>
      </div>

      <div className="mt-8 p-4 bg-amber-50 rounded-xl border border-amber-200">
        <p className="text-xs text-amber-700 text-center">
          💡 <strong>Pedagogical Note:</strong> The Raindrop Method guides students from broad unstructured ideas (Cloud) through
          structured WH-question scaffolding (Raindrops) to produce coherent narratives (Ground), systematically building
          independent writing proficiency.
        </p>
      </div>
    </section>
  );
}
